apiVersion: batch/v1
kind: Job
metadata:
  name: {{.JobName}}
spec:
  backoffLimit: 0
  template:
    spec:
      activeDeadlineSeconds: 3600
      containers:
        - command:
            - /opt/aqfer/log-wrap
            - --name
            - {{.JobName}}
            - --cid
            - {{.Cid}}
            - --run-id
            - {{.RunId}}
            - --config
            - s3://com.aqfer.dev.packages/adl/{{.Cid}}/{{.JobName}}/bundle.yaml
            - --dest
            - s3://{{.LogBucket}}/{{.Cid}}/$(POD_NAME)
            - --lakeview-domain
            - lakeview.api-dev.aqfer.net
            - --auth-domain
            - auth.api-dev.aqfer.net
            - --
            - sh
            - -c
            - |
              cp /etc/opt/aqfer/result.yaml .
              echo "Hello World!"
              sleep "60"
          env:
            - name: AQFER_LAKEVIEW_HOST
              value: https://lakeview.api-dev.aqfer.net
            - name: AQFER_REFRESH_TOKEN
              value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODM1MjM2NjYsImp0aSI6Ijc0ZGJlYzI5LWI2MzMtMTFlYy05Nzk5LTAyYmI2Y2Y2NDFjMiIsImlhdCI6MTY0OTMwOTI2NiwidXNlciI6IkhhcnNoYSIsImVtYWlsIjoiaGFyc2hhQHN0YXJ0c21hcnRsYWJzLmNvbSIsInNjb3BlIjp7ImNpZHMiOlsiYzAwOCJdfSwidHlwZSI6InJlZnJlc2hfdG9rZW4iLCJyb2xlcyI6WyJhcWZlcl9hZG1pbiJdLCJwdXJwb3NlIjoiY2xpZW50IG1nbXQgaW50ZWcgdGVzdCJ9.zqjSXzFo-22dXA8Yy0TQbAHpfyS5sKAggsNluRCIsX0"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: 965106989073.dkr.ecr.us-west-2.amazonaws.com/adl-uncertified:lite-v0.503.0
          name: {{.JobName}}
          resources:
            requests:
              memory: 400Mi
              cpu: 500m
      restartPolicy: Never
      serviceAccountName: spark
