apiVersion: batch/v1
kind: Job
metadata:
  name: {{.JobName}}
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    spec:
      activeDeadlineSeconds: 3600
      containers:
        - command:
            - /opt/aqfer/log-wrap
            - --name
            - {{.JobName}}
            - --cid
            - {{.Cid}}
            - --run-id
            - {{.RunId}}
            - --config
            - {{.UserParams.ConfigPath}}
            - --dest
            - s3://{{.LogBucket}}/{{.Cid}}/$(POD_NAME)
            - --credential-file
            - /etc/opt/aqfer/credentials.yaml
            - --
{{trimSuffix "\n" .UserParams.Executable | indent 12 }}  
          env:
            - name: AQFER_LAKEVIEW_HOST
              value: lakeview.api-dev.aqfer.net
            - name: AQFER_REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  key: DEV_AUTH_REFRESH_TOKEN
                  name: {{.Namespace}}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          name: {{.JobName}}
          image: ""
          imagePullPolicy: IfNotPresent
          resources: |
            {{trimSuffix "\n" .UserParams.Resources | indent 12 }}
      restartPolicy: Never
      serviceAccountName: spark
