apiVersion: batch/v1
kind: Job
metadata:
  name: {{.JobName}}
spec:
  backoffLimit: 0
  template:
    spec:
      activeDeadlineSeconds: 3600
      containers:
        - command:
            - /opt/aqfer/log-wrap
            - --name
            - {{.JobName}}
            - --cid
            - {{.Cid}}
            - --run-id
            - {{.RunId}}
            - --config
            - s3://com.aqfer.dev.packages/c008/sandbox/bundle.yaml
            - --dest
            - s3://{{.LogBucket}}/{{.Cid}}/$(POD_NAME)
            - --credential-file
            - /etc/opt/aqfer/credentials.yaml
            - --
            - /opt/aqfer/hetero-collate
            - driver
            - --config-file
            - /etc/opt/aqfer/config.yaml
            - --credentials-file
            - /etc/opt/aqfer/credentials.yaml
            - --stage
            - split
            - --stage
            - collate
            - --stage
            - sort
            - --stage
            - merge-plan
            - --stage
            - merge-do
            - --stage
            - transform
          env:
            - name: AQFER_LAKEVIEW_HOST
              value: lakeview.api-dev.aqfer.net
            - name: AQFER_REFRESH_TOKEN
              value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODM1MjM2NjYsImp0aSI6Ijc0ZGJlYzI5LWI2MzMtMTFlYy05Nzk5LTAyYmI2Y2Y2NDFjMiIsImlhdCI6MTY0OTMwOTI2NiwidXNlciI6IkhhcnNoYSIsImVtYWlsIjoiaGFyc2hhQHN0YXJ0c21hcnRsYWJzLmNvbSIsInNjb3BlIjp7ImNpZHMiOlsiYzAwOCJdfSwidHlwZSI6InJlZnJlc2hfdG9rZW4iLCJyb2xlcyI6WyJhcWZlcl9hZG1pbiJdLCJwdXJwb3NlIjoiY2xpZW50IG1nbXQgaW50ZWcgdGVzdCJ9.zqjSXzFo-22dXA8Yy0TQbAHpfyS5sKAggsNluRCIsX0"
            - name: PEPPER
              value: aqfer
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: 965106989073.dkr.ecr.us-west-2.amazonaws.com/adl-uncertified:1.2322.0
          name: {{.JobName}}
          resources:
            requests:
              cpu: 500m
              memory: 400Mi
      restartPolicy: Never
      serviceAccountName: spark
