work_area: gs://c008.preprod_gcs@tmp.amdp.preprod.aqfer.com/amdp-services/collator/examples/example-2/work_area/{{env "POD_NAME"}}
separate_transform_stage: true
inputs:
  - name: events
    key:
      - user_id
    locations:
      - files: 
          - gs://c008.preprod_gcs@tmp.amdp.preprod.aqfer.com/gcp-lakeview-integ-test/collator/examples/example-2/input/part-00000-da99167e-9de1-4b20-ae1b-ca77524e149c-c000.csv
    format: csv
    csv:
      has_header: true
      schema:
        type: record
        name: event
        fields:
          - name: user_id
            type: string
          - name: category
            type: string
          - name: subcategory
            type: string
          - name: product_name
            type: string
          - name: quintile
            type: int
sort:
  key_names:
    - user_id
  project:
    '.':
      field_names: [ 'user_id' ]
transform:
  - insert_columns:
      - name: hashed_user_id
        before: user_id
        type: string
        expr:
          template: 'XI{{print .user_id}}'
        use:
          - user_id
outputs:
  - destination: gs://c008.preprod_gcs@tmp.amdp.preprod.aqfer.com/amdp-services/collator/examples/example-2/output
    project:
      '.':
        field_names: [ 'hashed_user_id', 'events' ]
capacity:
  split_stage:
    in_proc_executor:
      num_workers: 12
  collate_stage:
    in_proc_executor:
      num_workers: 32
  sort_stage:
    in_proc_executor:
      num_workers: 3
  merge_plan_stage:
    in_proc_executor:
      num_workers: 20
  merge_do_stage:
    in_proc_executor:
      num_workers: 20
  transform_stage:
    in_proc_executor:
      num_workers: 20
