- path: /etc/opt/aqfer/result.yaml
  permission: 0770
  format: yaml
  contents:
    lakeview_metrics:
      - data_channel: "integ_test_input"
        type: "input"
        record_schema: "test"
        file_count: 1
        error_file_count: 0
        record_count: 99999999
        quarantine_record_count: 0
        byte_count: 5384214
      - data_channel: "integ_test_output"
        type: "output"
        file_count: 1
        record_count: 7664
        byte_count: 1602994