apiVersion: batch/v1
kind: Job
metadata:
  name: {{.JobName}}
spec:
  backoffLimit: 0
  template:
    spec:
      activeDeadlineSeconds: 3600
      containers:
        - command:
            - /opt/aqfer/log-wrap
            - --name
            - {{.JobName}}
            - --cid
            - {{.Cid}}
            - --run-id
            - {{.RunId}}
            - --config
            - {{.ConfigBundleS3Path}}
            - --dest
            - s3://{{.LogBucket}}/{{.Cid}}/{{.Namespace}}/$(POD_NAME)
            - --credential-file
            - /etc/opt/aqfer/credentials.yaml
            - --
            - /opt/aqfer/hetero-collate
            - driver
            - --config-file
            - /etc/opt/aqfer/config.yaml
            - --credentials-file
            - /etc/opt/aqfer/credentials.yaml
            - --stage
            - split
            - --stage
            - collate
            - --stage
            - sort
            - --stage
            - merge-plan
            - --stage
            - merge-do
            - --stage
            - transform
          env:
            - name: a
              value: b
            - name: AWS_REGION
              value: us-west-2
            - name: AQFER_LAKEVIEW_HOST
              value: lakeview.api-dev.aqfer.net
            - name: AQFER_REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  key: DEV_AUTH_REFRESH_TOKEN
                  name: {{.Namespace}}
            - name: BOT_AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: BOT_AWS_ACCESS_KEY
                  name: "c008"
            - name: BOT_AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: BOT_AWS_SECRET_KEY
                  name: "c008"
            - name: PEPPER
              value: aqfer
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: 965106989073.dkr.ecr.us-west-2.amazonaws.com/adl-uncertified:1.2034.0
          name: {{.JobName}}
          resources:
            requests:
              cpu: 500m
              memory: 400Mi
      restartPolicy: Never
      serviceAccountName: spark
